## Preprocessing

In [65]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [66]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df=application_df.drop(['EIN', 'NAME'], axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [67]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [68]:
# Look at APPLICATION_TYPE value counts for binning
app_type_counts = application_df['APPLICATION_TYPE'].value_counts()

In [69]:
# Look at CLASSIFICATION value counts for binning
classification_type_count = application_df['APPLICATION_TYPE'].value_counts()
classification_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [70]:
# Define a cutoff value
cutoff_value = 100

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [71]:
# Look at CLASSIFICATION value counts for binning
classification_type_count = application_df['CLASSIFICATION'].value_counts()
classification_type_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [72]:
#  CLASSIFICATION value counts >1
classification_type_count_1= classification_type_count[classification_type_count>1]
classification_type_count_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [73]:

# Create a list of classifications to be replaced with "Other"
cutoff_value = 1000
classifications_to_replace = classification_type_count_1[classification_type_count_1 <= cutoff_value].index.tolist()
# classifications_to_replace
# classifications_to_replace.append('Other')
# Replace in dataframe
for clf in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(clf,"Other")

# # Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2235
C3000     1918
C2100     1883
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1248        1
C2600        1
C1580        1
C6100        1
C1820        1
C1900        1
C2570        1
C1570        1
C3700        1
C2500        1
C1283        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [74]:
# Convert categorical data to numeric with `pd.get_dummies`
# Specify the columns that need to be converted to numeric
categorical_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

# Use pd.get_dummies to convert categorical columns to numeric
application_df = pd.get_dummies(application_df, columns=categorical_columns)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [75]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop('IS_SUCCESSFUL', axis=1)
y = application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [78]:
X.shape

(34299, 69)

In [79]:
y.shape

(34299,)

In [77]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [103]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = 69
hidden_nodes_layer1 =  16
hidden_nodes_layer2 = 16
nn_model = tf.keras.models.Sequential()

# 69  is correct?

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=69))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 16)                1120

 dense_10 (Dense)            (None, 16)                272

 dense_11 (Dense)            (None, 1)                 17

=================================================================
Total params: 1409 (5.50 KB)
Trainable params: 1409 (5.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [100]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [101]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7377
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7386
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7381
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7376
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7382
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5409 - accuracy: 0.7383
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7385
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7379
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7378
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7384
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7377
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7380
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7390
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7382
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7383
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5404 - accuracy: 0.7382
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7387
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7379
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7379
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7374
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7384
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7378
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7380
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7390
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7377
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7382
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7382
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7383
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7373
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7381
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7386
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7392
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7388
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7386
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7379
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7386
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7386
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7390
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5399 - accuracy: 0.7389
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7390
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7378
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7383
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7380
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7385
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7376
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7385
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7387
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7390
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7378
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7380
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7385
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7390
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7390
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7383
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7382
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7386
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7380
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7382
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7381
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7388
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7385
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7388
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7392
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7388
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7383
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7378
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7390
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7390
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7386
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7396
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7391
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7391
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7397
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7383
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7389
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7384
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7387
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7390
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7388
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7384
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7383
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7384
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7396
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7383
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7381
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7388
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7388
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7387
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7388
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7393
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7388
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7389
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7388
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7389
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7390
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7386
268/268 - 0s - loss: 0.5594 - accuracy: 0.7248 - 451ms/epoch - 2ms/step
Loss: 0.5594016909599304, Accuracy: 0.724781334400177

In [94]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5571 - accuracy: 0.7256 - 346ms/epoch - 1ms/step
Loss: 0.5571494102478027, Accuracy: 0.7255976796150208

In [99]:
# Export our model to HDF5 file
nn_model.save("AlphabetSoupCharity.h5")
# where can i see this save?